version: "3.8"

#-------------------------------------------------------------
# Automated solution for integrating continuous monitoring systems Prometheus
# docker-compose version: "3.8"
# For full details on what each version includes and how to upgrade, see: 
# Compose and Docker compatibility matrix
# https://docs.docker.com/compose/compose-file/
#
# Copyleft (c) by Alex Sonar 2021
#-------------------------------------------------------------

services:

  prometheus:
    image: NGINX
    ports:
      - "9000:9000" # PROMETHEUS_PORT_MONITORING_SERVER
      - "9090:9090" # PROMETHEUS_PORT_MONITORING_ALT_SERVER
      - "9100:9100" # PROMETHEUS_PORT_NODE_EXPORTER
      - "9093:9093" # PROMETHEUS_PORT_ALERT_MANAGER
      - "5000:5000" # PROMETHEUS_PORT_BASE_CLUSTER_N0
      - "5001:5001" # PROMETHEUS_PORT_BASE_CLUSTER_N1
      - "5002:5002" # PROMETHEUS_PORT_BASE_CLUSTER_N2
      - "3000:3000" # PROMETHEUS_PORT_GRAFANA
      - "80:80"     # PROMETHEUS_PORT_WEB_PROX
      - "443:443"   # PROMETHEUS_PORT_WEB_PROX_LTS
      - "2222:22"   # PROMETHEUS_PORT_SSH
    volumes:
      - $VOL_PROMETHEUS_CORE:/etc/prometheus/
      - /home/$USER/prometheus:/etc/prometheus/
      - ${PROMETHEUS_VOL_DATA}:/prometheus
    # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx:/etc/nginx 
    environment:
      - NGINX_HOST=prometheus-monitoring-dev.net
      - NGINX_PORT=80
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-storage.local.target-heap-size=524288000'
    restart: unless-stopped
    networks:
      - prometheus-monitor-backend-dev
      - prometheus-monitor-frontend-dev
    labels:
      io.prometheus.service.name:  "prometheus-dev"
      io.prometheus.service.group: "monitoring-dev"
      io.prometheus.service.title: "prometheus-monitoring-dev"

networks:
  prometheus-monitor-backend-$ENV_PROMETHEUS:
    driver: bridge
  prometheus-monitor-frontend-$ENV_PROMETHEUS:
    driver: bridge